services:
  - type: web
    name: pixturbinado
    env: static
    buildCommand: npm run build
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
